###################################
# HORDES
###################################

# Minimum logs level
# DEBUG, INFO, WARNING, ERROR, NONE
logs_level : DEBUG

# Games config
games:
    default:
    
        # World name
        world: world
        
        # Difficulty level (for the number of zombies only)
        # PEACEFULL, EASY, HARD, EXTREME
        difficulty: EASY
        
        # List of mobs allowed to spawn other than Zombie
        mobs_allowed: [Cow, Chicken, Pig, Wolf]
        
        # Configure what evolved mobs are allowed to do
        # permissions : move, attack_player, attack_mob, break_block, place_block, use_object
        mobs_permissions:
            Zombie: [move]

###################################
# EvolvedMobs
###################################

# Distance for reaching a location
location_reached:
    x: 1
    y: 0
    z: 1
